name: Build and Deploy Documentation

on:
  push:
    branches:
      - '!gh-pages'
      - 'master'
    paths:
      - 'core/**'
      - 'scripts/**'
      - 'src/**'
      - '!**/README.*'
      - '!dtcw'
      - '!test/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'scripts/**'
      - 'src/**'
      - '!**/README.*'
      - '!dtcw'
      - '!test/**'
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
        jdk: [adopt]
      fail-fast: false
    name: Java ${{ matrix.jdk }}-${{ matrix.java }} Build

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install required packages
        run: sudo apt-get install -y graphviz shellcheck pandoc

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Build and Generate Site with docToolchain
        run: |
          ./dtcw generatesite

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/jbake/microsite/output  # Adjust if your output folder differs

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.jdk }}-${{ matrix.java }}
          path: build/reports/tests/test/
